name: base
channels:
  - conda-forge
dependencies:
  - python=3.8 
  - numpy
  - pandas
  - jupyterlab
  - altair
  - altair_saver
  - nbgitpuller
  - jupyter-server-proxy
  - jupyterlab-spellchecker
  - pyyaml
  - toml
  - matplotlib
  - jupyterlab-git
  - cython
  - bash_kernel
  - vega-datasets 